#-------------------------------
# General Site Settings

menu:
- {name: '作品', url: ''}
- {name: '活动', url: 'pages/events.html'}
- {name: '团队介绍', url: 'pages/about.html'}
- {name: '联系我们', url: 'pages/contact.html'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: '声音与影像、交互、装置艺术探索团体——19声音Lab '
  rel-author: 'https://github.com/xuwenjiang/'
  rel-publisher: 'https://github.com/xuwenjiang/'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
# google-analytics-ua: 'UA-112060364-3'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'thathungrymind'

contact: >
  #### 联系方式
  
  许瀚  电话：18001178173    电子邮箱：hanxucomposerbeijing@outlook.com    微信：xuhanJohn

  
  何凝  电话：15001246202    电子邮箱：147172258@qq.com     微信：banabro
  
  
  快递地址 北京市朝阳区北京新天地2期1号楼1单元

#-------------------------------
# Work Section

projects:
- {name: 'Project One', folder: 'proj-1', file: 'projects/proj-1.html'}
- {name: 'Project Two', folder: 'proj-2', file: 'projects/proj-2.html'}
- {name: 'Project Three', folder: 'proj-3', file: 'projects/proj-3.html'}
- {name: 'Project Four', folder: 'proj-4', file: 'projects/proj-4.html'}
- {name: 'Project Five', folder: 'proj-5', file: 'projects/proj-5.html'}

#-------------------------------
# Contact Section

social:
- {icon: 'twitter', link: '#'}
- {icon: 'instagram', link: '#'}
- {icon: 'github', link: '#'}
- {icon: 'linkedin', link: '#'}
- {icon: 'envelope', link: 'mailto:#'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
